config/routes.rb
Rails.application.routes.draw do
  resources :posts do
    resources :comments do
    end
  end
  get '/signup' => 'users#new'
  post '/users' => 'users#create'

  get '/signin' => 'sessions#new'
  post '/signin' => 'sessions#create'
  get '/signout' => 'sessions#destroy'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :user
  belongs_to :post
  validates :content, :presence => true
end

app/models/post.rb
class Post < ActiveRecord::Base
  # belongs_to :user
  has_many :comments
  validates :title, :presence => true
  validates :link, :presence => true
end

app/models/user.rb
# require 'bcrypt'
class User < ApplicationRecord
  has_many :posts
  has_many :comments
  attr_accessor :password
  validates_confirmation_of :password
  validates :email, :presence => true, :uniqueness => true
  before_save :encrypt_password

  def encrypt_password
    self.password_salt = BCrypt::Engine.generate_salt
    self.password_hash = BCrypt::Engine.hash_secret(password,password_salt)
  end

  def self.authenticate(email, password)
    user = User.find_by "email = ?", email
    if user && user.password_hash == BCrypt::Engine.hash_secret(password, user.password_salt)
      user
    else
      nil
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  helper_method :current_user

  def current_user
    if session[:user_id]
      @current_user ||= User.find(session[:user_id])
    end
  end
  def authorize
    if !current_user
      flash[:alert] = "You aren't authorized to visit that page."
      redirect_to '/'
    end
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  def show
    @comment = Comment.find(params[:id])
    render :show
  end

  def new
    @post = Post.find(params[:post_id])
    @comment = Comment.new
    @user = current_user
    render :new
  end

  def update
    @comment = Comment.find(params[:id])
    @comment.update(comment_params)
    # binding.pry
    render :show
  end

  def create
    @post = Post.find(params[:post_id])
    @comment = Comment.new(comment_params)
    if @comment.save
      redirect_to post_path(@post)
    else
      render :new
    end
  end

  private
  def comment_params
    params.require(:comment).permit(:content, :user_id, :post_id)
  end
end

app/controllers/just_another_controller.rb
class JustAnotherController < ApplicationController
  before_action :authorize, only: [:secret]

  def secret
  end

end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  def index
    @posts = Post.order(points: :desc, created_at: :desc).all
    render :index
  end

  def show
    @post = Post.find(params[:id])
    render :show
  end

  def new
    @post = Post.new
    render :new
  end

  def update
    @post = Post.find(params[:id])
    @post.update(post_params)
    # binding.pry
    render :show
  end

  def create
    @post = Post.new(post_params)
    if @post.save
      redirect_to post_path(@post)
    else
      render :new
    end
  end

  private
  def post_params
    params.require(:post).permit(:title, :link, :points)
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def create
    @user = User.authenticate(params[:email], params[:password])
    if @user
      flash[:notice] = "You've signed in."
      session[:user_id] = @user.id
      redirect_to "/posts"
    else
      flash[:alert] = "There was a problem signing in. Please try again."
      redirect_to signin_path
    end
  end

  def destroy
    session[:user_id] = nil
    flash[:notice] = "You've signed out."
    redirect_to "/posts"
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      flash[:notice] = "You've successfully signed up!"
      session[:user_id] = @user.id
      redirect_to "/posts"
    else
      flash[:alert] = "There was a problem signing up."
      redirect_to '/signup'
    end
  end

  private

  def user_params
    params.require(:user).permit(:email, :password, :password_confirmation)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/comments/new.html.erb
<h1>New post</h1>
<%= render "layouts/form_comment" %>

app/views/layouts/_errors.html.erb
<% if @post.errors.any? %>
  <h3>Please fix these errors:</h3>
  <ul>
    <% @post.errors.full_messages.each do |message| %>
      <li><%= message %></li>
    <% end %>
  </ul>
<% end %>

app/views/layouts/_errors_comment.html.erb
<% if @comment.errors.any? %>
  <h3>Please fix these errors:</h3>
  <ul>
    <% @comment.errors.full_messages.each do |message| %>
      <li><%= message %></li>
    <% end %>
  </ul>
<% end %>

app/views/layouts/_form.html.erb
<%= render "layouts/errors", :object => @post %>
<%= form_for @post do |f| %>
  <%= f.label :title %>
  <%= f.text_field :title %>
  <%= f.label :link %>
  <%= f.text_field :link %>
  <%= f.hidden_field :points, :value => 0 %>
  <%= f.submit %>
<% end %>

app/views/layouts/_form_comment.html.erb
<%= render "layouts/errors_comment", :object => @comment %>
<%= form_for [@post, @comment] do |f| %>
  <%= f.label :content %>
  <%= f.text_field :content %>
  <%= f.hidden_field :post_id, :value => @post.id %>
  <%= f.hidden_field :user_id, :value => @user.id%>
  <%= f.hidden_field :points, :value => 0 %>
  <%= f.submit %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>HackerNews</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <% if current_user %>
      <%= current_user.email %> | <%= link_to "Sign out", '/signout' %>
    <% else %>
      <%= link_to "Sign up", 'signup' %> | <%= link_to "Sign in", '/signin' %>
    <% end %>

    <%= flash[:alert] %>
    <%= flash[:notice] %>

    <%= yield %>
  </body>
</html>

app/views/posts/index.html.erb
<h1>Posts</h1>

<%= link_to "Create post", new_post_path %>

<ul>
  <% @posts.each do |post| %>
    <li><%= link_to post.title, post_path(post) %><br>Points: <%= post.points %></li>

  <% end %>
</ul>

app/views/posts/new.html.erb
<h1>New post</h1>
<%= render "layouts/form" %>

app/views/posts/show.html.erb
<%= @post.title %><br>
Points: <%= @post.points %><br>
<%= link_to @post.link.to_s, @post.link%><br>
<% if current_user %>
  <%= form_for @post, :url => post_path do |f| %>
    <%= f.hidden_field :title, :value => @post.title %>
    <%= f.hidden_field :link, :value => @post.link  %>
    <%= f.hidden_field :points, :value => @post.points + 1  %>
    <%= f.submit "Up-vote" %>
  <% end %>
<%end%>
<% @post.comments.each do |comment| %>
<%= comment.user.email %><br>
<%= comment.content %><br>
<% end %>
<%= link_to "New comment", new_post_comment_path(@post) %>


<%= link_to "Home", posts_path %><br>

app/views/users/new.html.erb
<h1> Sign up</h1>
<%= form_for @user do |f| %>
  <%= f.label "Email" %>
  <%= f.text_field :email %>
  <%= f.label "Password" %>
  <%= f.password_field :password %>
  <%= f.label :password_confirmation %>
  <%= f.password_field :password_confirmation %>
  <%= f.submit "Sign Up" %>
<% end %>